#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(HYDRO_PUMP) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(WEATHER_BALL) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(VOLT_SWITCH) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(TRAILBLAZE) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
	F(ROOST) \
	F(FOCUS_BLAST) \
	F(ENERGY_BALL) \
	F(FALSE_SWIPE) \
	F(SCALD) \
	F(FLING) \
	F(CHARGE_BEAM) \
	F(ENDURE) \
	F(DRAGON_PULSE) \
	F(DRAIN_PUNCH) \
	F(WILL_O_WISP) \
	F(ACROBATICS) \
	F(NASTY_PLOT) \
	F(EARTH_POWER) \
	F(SHADOW_CLAW) \
	F(PAYBACK) \
	F(RECYCLE) \
	F(GIGA_IMPACT) \
	F(ROCK_POLISH) \
	F(DAZZLING_GLEAM) \
	F(STONE_EDGE) \
	F(AVALANCHE) \
	F(THUNDER_WAVE) \
	F(GYRO_BALL) \
	F(SWORDS_DANCE) \
	F(STEALTH_ROCK) \
	F(THROAT_CHOP) \
	F(PLAY_ROUGH) \
	F(DARK_PULSE) \
	F(ROCK_SLIDE) \
	F(X_SCISSOR) \
	F(DRAGON_TAIL) \
	F(FLAME_CHARGE) \
	F(POISON_JAB) \
	F(ZEN_HEADBUTT) \
	F(GRASS_KNOT) \
	F(SMACK_DOWN) \
	F(HURRICANE) \
	F(U_TURN) \
	F(SUBSTITUTE) \
	F(FLASH_CANNON) \
	F(TRICK_ROOM) \
	F(WILD_CHARGE) \
	F(SUCKER_PUNCH) \
	F(PSYSHOCK) \
	F(LOW_SWEEP) \
	F(ALLURING_VOICE) \
	F(PSYCHIC_NOISE) \
	F(ROCK_BLAST) \
	F(CURSE) \
	// F(WATER_PULSE) \
	// F(FRUSTRATION) \
	// F(ATTRACT) \
	// F(SHOCK_WAVE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
